on:
  push:
    branches: [main]

jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.ruirezende.com.br
          username: ruirezen
          password: ${{ secrets.ftp_password }}
          server-dir: /domains/ruirezende.com.br/public_html/